apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/
commonLabels:
  deploy-env: prod
images:
  - name: nginx
    newName: asia-east1-docker.pkg.dev/gamania-test-417905/gke-repository/nginx
    newTag: v3
replicas:
  - name: nginx-deployment
    count: 3
