name: kustomize
on:
  workflow_call:
  push:
    branches:
      - main
    paths:
      - 'kustomize/**'

jobs: 
  kustomize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}
  
      - name: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          cluster_name: ${{ vars.GKE_CLUSTER_NAME }}
          location: ${{ vars.REGION }}

      # - name: Setup Kustomize
      #   run: |
      #     curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
      #     sudo mv kustomize /usr/local/bin/

      - name: Kustomize Build
        run: kubectl apply -k kustomize/overlays/prod
