name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

      # retag acr image
      - name: retag acr image
        run: gcloud artifacts docker tags add ${{ vars.ACR_IMAGE_URL }}:${{ github.sha }} ${{ vars.ACR_IMAGE_URL }}:${{ github.ref_name }}
      
      # push tag to kustomize file
      - name: yq - portable yaml processor
        uses: mikefarah/yq@v4.42.1

      - name: Add git config
        run: |
          git config --global user.email "github-actions@gamania.test"
          git config --global user.name "github-actions"
  
      - name: push tag to kustomize
        run: |
          yq eval -i '.images[0].newTag = "${{ github.ref_name }}"' kustomize/overlays/prod/kustomization.yaml
          git add kustomize/overlays/prod/kustomization.yaml
          git commit -m "Update image tag to ${{ github.ref_name }}"
          git push origin main
  
  deploy:
    uses: ./.github/workflows/kustomize.yaml
